Base layout
platanus/fdbk pull request #2
Opened 2022-11-14 19:19 UTC by gmq

### Contexto
Aplicación sandbox para trainees
​
### Qué se esta haciendo
- Se agrega estilo básico (fuentes, layout)
- Se configuran algunas cosas que deberían estar en potassium (eslint, plugins, csrftoken) :awesomeface:
- Se agregan algunos componentes básicos
- Se configura para que funcione devise por API
- Se agrega componente para hacer login/register

-----------
#### Info Adicional (pantallazos, links, fuentes, etc.)
![image](https://user-images.githubusercontent.com/472791/201746420-6d65bc11-4b9e-4315-80b8-5428b44b668d.png)
![Screen Shot 2022-11-14 at 16 17 07](https://user-images.githubusercontent.com/472791/201746467-9ffb9cec-5a49-461a-a2b5-ecb31799913f.png)

2022-11-14 19:24 UTC, ldlsegovia approved these changes
Impecable!

2022-11-14 19:24 UTC, ldlsegovia commented on app/javascript/components/the-header.vue
> +      Nest
No le pondría nest para no generar confusión. Trainee App? Fdbk? Platanus? no sé

2022-11-14 19:27 UTC, gmq commented on app/javascript/components/the-header.vue
> +      Nest
Ahí le cambié el nombre 👍

2022-11-14 19:29 UTC, ldlsegovia approved these changes

2022-11-16 13:59 UTC, difernandez requested changes
Bueena se ve bacán! Dejo un detalle en el template y una duda

2022-11-16 13:59 UTC, difernandez commented on app/javascript/components/base-checkbox.vue
> +    :class="$attrs.class"
este no pasaría automáticamente ya al label si no se setea `inheritAttrs: false`?

2022-11-16 13:59 UTC, difernandez commented on app/javascript/components/base-input.vue
> +    :class="attrs.class"
idem lo de `inheritAttrs`

2022-11-16 13:59 UTC, difernandez commented on app/views/devise/registrations/new.html.erb
> +  <user-session class="self-center" mode="register"><user-session>
falta el `/` en el tag de cierre

2022-11-16 13:59 UTC, difernandez commented on app/views/devise/sessions/new.html.erb
> +  <user-session class="self-center" mode="login"><user-session>
idem `/`

2022-11-16 14:12 UTC, gmq commented on app/javascript/components/base-checkbox.vue
> +    :class="$attrs.class"
Toda la razón

2022-11-16 14:16 UTC, difernandez approved these changes

2022-11-16 14:16 UTC, merged